services:
  backend:
    build: ./backend
    ports:
      - "3002:3002"
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongodb:27017/test
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:3002

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
